runtime: python
env: flex # other option would be standard
entrypoint: waitress-serve main:serve
# More entrypoints that I tried:
#entrypoint: gunicorn -b :$PORT main:app - For linux
#entrypoint: waitress-serve --listen=*:5000 main:app - For windows with port 5000

runtime_config:
  python_version: 3

# This is not a safe way to do it since the repo is public and shared.
# Added to env_vars.yaml and passed on gitignore.
#env_variables:
#  BASIC_AUTH_USERNAME: zzzzz
#  BASIC_AUTH_PASSWORD: zzzz
includes:
- env_vars.yaml
